### ISSUE TITLE
send organization-name after creating mapping

### ISSUE THREAD

**Issue by fpriyatna** [oeg-upm/mappingpedia-userinterface#13]
send CKAN organization-name (eg zaragoza_spain) instead of CKAN organization_id (2cc474a3-d0d6-407d-96ae-2cbf10f42e4c) after creating mappings

**Comment by ahmad88me** [comment]
@fpriyatna Can you elaborate on that, I didn't understand this clearly

**Comment by fpriyatna** [comment]
thanks!
