### ISSUE TITLE
JSON files from Zaragoza is not working in the editor

### ISSUE THREAD

**Issue by ahmad88me** [oeg-upm/mappingpedia-userinterface#9]

**Comment by ahmad88me** [comment]
@fpriyatna Hi Freddy, The issue is that zaragoza json files can't be downloaded (you can try with wget). after trying to check the headers the browser sends (as it works on the browser). I discovered that for the json to be downloaded the header key `Accept` with some value has to be sent, which I think should not be required[1]. For the time being, I'll force this header value.

[1] headers = {
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
}

**Comment by fpriyatna** [comment]
The headers now appear, but I got an error after clicking the create mapping button.

**Comment by fpriyatna** [comment]
[generate_mappings_error.pdf](https://github.com/oeg-upm/mappingpedia-userinterface/files/1554827/generate_mappings_error.pdf)

**Comment by fpriyatna** [comment]
Thanks!
